"""create new table days_to_hire

Revision ID: 042ffed28be5
Revises: 991ecb2bf269
Create Date: 2025-07-25 19:48:45.537704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042ffed28be5'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_to_hire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('min_days', sa.Float(), nullable=False),
    sa.Column('avg_days', sa.Float(), nullable=False),
    sa.Column('max_days', sa.Float(), nullable=False),
    sa.Column('job_postings_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('days_to_hire', schema='public')
    # ### end Alembic commands ###
